import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/common/Navigation";
import Footer from "@/components/common/Footer";
import { Toaster } from "sonner";
import { WorkoutProvider } from "@/contexts/Workout";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutProvider>
          <Navigation />
          <main className="container mx-auto flex-1 flex flex-col gap-6 px-6 py-6 md:px-6 md:py-12">
            {children}
          </main>
          <Footer />
        </WorkoutProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
